import type { FlowPalette } from './flowPalettes'
type RenderCanvas = HTMLCanvasElement | OffscreenCanvas
const vertex = `#version 300 es
in vec2 a_position; out vec2 v_uv; void main(){v_uv=a_position*.5+.5;gl_Position=vec4(a_position,0.,1.);}`
const fragment = `#version 300 es
precision highp float; in vec2 v_uv; out vec4 outColor; uniform vec2 u_resolution; uniform float u_time; uniform vec3 u_colors[5];
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);} float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+1.),f.x),f.y);} float fbm(vec2 p){float v=0.,a=.52;for(int i=0;i<5;i++){v+=a*noise(p);p=p*2.03+vec2(17.2,9.1);a*=.48;}return v;}
vec3 pal(float t){t=clamp(t,0.,.999);float x=t*4.,f=smoothstep(0.,1.,fract(x));int i=int(floor(x));if(i==0)return mix(u_colors[0],u_colors[1],f);if(i==1)return mix(u_colors[1],u_colors[2],f);if(i==2)return mix(u_colors[2],u_colors[3],f);return mix(u_colors[3],u_colors[4],f);}
void main(){vec2 uv=v_uv;uv.x*=u_resolution.x/u_resolution.y;float t=u_time*.045;vec2 q=vec2(fbm(uv*1.45+vec2(t,-t*.7)),fbm(uv*1.3+vec2(-t*.55,t*.8)));vec2 r=vec2(fbm(uv*2.+q*1.7+vec2(t*.7,0)),fbm(uv*1.8+q*1.35-vec2(0,t*.5)));float field=fbm(uv*1.18+r*1.75+q*.7);float ribbon=smoothstep(.36,.78,field+sin((uv.x+uv.y)*2.3+r.x*2.)*.12);float d=clamp(v_uv.x*.48+(1.-v_uv.y)*.28+field*.42,0.,1.);vec3 c=mix(pal(d),pal(clamp(d+.2,0.,1.)),ribbon*.28);c+=vec3(1.)*pow(max(0.,1.-abs(field-.57)*6.),3.)*.09;outColor=vec4(c,1.);}`
const rgb=(hex:string):[number,number,number]=>{const v=parseInt(hex.slice(1),16);return [((v>>16)&255)/255,((v>>8)&255)/255,(v&255)/255]}
function compile(gl:WebGL2RenderingContext,type:number,source:string){const shader=gl.createShader(type);if(!shader)throw Error('shader');gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(shader)??'compile');return shader}
export class FlowRenderer { private gl:WebGL2RenderingContext; private program:WebGLProgram; private resolution:WebGLUniformLocation; private time:WebGLUniformLocation; private colors:WebGLUniformLocation; private canvas: RenderCanvas;
 constructor(canvas:RenderCanvas,{preserveDrawingBuffer=false}:{preserveDrawingBuffer?:boolean}={}){this.canvas=canvas;const gl=canvas.getContext('webgl2',{alpha:false,antialias:false,depth:false,powerPreference:'low-power',preserveDrawingBuffer}) as WebGL2RenderingContext|null;if(!gl)throw Error('WebGL2 unavailable');this.gl=gl;const p=gl.createProgram();if(!p)throw Error('program');gl.attachShader(p,compile(gl,gl.VERTEX_SHADER,vertex));gl.attachShader(p,compile(gl,gl.FRAGMENT_SHADER,fragment));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p)??'link');this.program=p;this.resolution=gl.getUniformLocation(p,'u_resolution')!;this.time=gl.getUniformLocation(p,'u_time')!;this.colors=gl.getUniformLocation(p,'u_colors[0]')!;const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const a=gl.getAttribLocation(p,'a_position');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0)}
 resize(w:number,h:number,dpr:number){this.canvas.width=Math.max(1,Math.round(w*dpr));this.canvas.height=Math.max(1,Math.round(h*dpr));this.gl.viewport(0,0,this.canvas.width,this.canvas.height)}
 draw(seconds:number,palette:FlowPalette){const gl=this.gl;gl.useProgram(this.program);gl.uniform2f(this.resolution,this.canvas.width,this.canvas.height);gl.uniform1f(this.time,seconds);gl.uniform3fv(this.colors,palette.flatMap(rgb));gl.drawArrays(gl.TRIANGLES,0,3)} destroy(){this.gl.deleteProgram(this.program)} }
