import { useEffect, useRef, useState } from 'react'
import { FlowRenderer } from '../background/FlowRenderer'
import { getFlowPalette, type HarborScene } from '../background/flowPalettes'
const REDUCED='(prefers-reduced-motion: reduce)'
const isWebGlUnavailable=(value:unknown)=>value==='WebGL2 unavailable'||(value instanceof Error&&value.message==='WebGL2 unavailable')
export function FlowBackground({scene}:{scene:HarborScene}){const ref=useRef<HTMLCanvasElement>(null);const initialScene=useRef(scene);const [ready,setReady]=useState(false);const [fallback,setFallback]=useState(false)
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;let worker:Worker|undefined,renderer:FlowRenderer|undefined,raf=0,readyRaf=0,stopped=false,readyReported=false,fallbackActive=false,last=0;const media=matchMedia(REDUCED);const palette=()=>{const value=document.documentElement.dataset.harborScene;const current=value==='garden'||value==='stellar'||value==='dusk'?value:initialScene.current;return getFlowPalette(current,document.documentElement.classList.contains('light-theme'))};const size=()=>({width:innerWidth,height:innerHeight,dpr:Math.min(devicePixelRatio||1,1.25)});const canRun=()=>!document.hidden&&!document.documentElement.classList.contains('harbor-intro-active');const markReady=()=>{if(readyReported||fallbackActive)return;readyReported=true;readyRaf=requestAnimationFrame(()=>{readyRaf=requestAnimationFrame(()=>{if(!stopped&&!fallbackActive)setReady(true)})})};const activateCssFallback=(reason:unknown)=>{fallbackActive=true;cancelAnimationFrame(readyRaf);worker?.terminate();worker=undefined;if(!stopped){setReady(false);setFallback(true)}if(isWebGlUnavailable(reason))console.info('[flow-background] WebGL2 unavailable; CSS fallback active');else console.warn('[flow-background] CSS fallback active:',reason)}
 const main=()=>{try{renderer=new FlowRenderer(canvas,{preserveDrawingBuffer:true});renderer.resize(size().width,size().height,size().dpr);const draw=(now:number)=>{if(stopped)return;if(canRun()&&(media.matches?last===0:now-last>=1000/30)){renderer?.draw(media.matches?0:now/1000,palette());last=now;markReady()}raf=requestAnimationFrame(draw)};raf=requestAnimationFrame(draw)}catch(error){activateCssFallback(error)}}
 if(!import.meta.env.DEV&&'transferControlToOffscreen' in canvas&&typeof Worker!=='undefined'){try{worker=new Worker(new URL('../background/flow.worker.ts',import.meta.url),{type:'module'});worker.onmessage=({data})=>{if(data.type==='frame')markReady();else if(data.type==='error')activateCssFallback(data.message)};worker.onerror=(event)=>{event.preventDefault();activateCssFallback('Flow worker runtime failed')};worker.onmessageerror=()=>activateCssFallback('Flow worker message failed');const initialSize=size();canvas.width=Math.max(1,Math.round(initialSize.width*initialSize.dpr));canvas.height=Math.max(1,Math.round(initialSize.height*initialSize.dpr));const offscreen=canvas.transferControlToOffscreen();worker.postMessage({type:'init',canvas:offscreen,...initialSize,palette:palette(),reducedMotion:media.matches,running:canRun()},[offscreen])}catch{console.info('[flow-background] worker unavailable; trying main-thread renderer');worker?.terminate();worker=undefined;main()}}else main()
 const sync=()=>{const s=size();if(worker){worker.postMessage({type:'resize',...s});worker.postMessage({type:'palette',palette:palette()});worker.postMessage({type:'motion',reducedMotion:media.matches,running:canRun()})}else if(renderer){renderer.resize(s.width,s.height,s.dpr);if(media.matches){last=0;renderer.draw(0,palette());markReady()}}};const observer=new MutationObserver(sync);observer.observe(document.documentElement,{attributes:true,attributeFilter:['class','data-harbor-scene']});addEventListener('resize',sync);document.addEventListener('visibilitychange',sync);media.addEventListener('change',sync)
 return()=>{stopped=true;cancelAnimationFrame(raf);cancelAnimationFrame(readyRaf);worker?.terminate();renderer?.destroy();observer.disconnect();removeEventListener('resize',sync);document.removeEventListener('visibilitychange',sync);media.removeEventListener('change',sync)}},[])
 return <canvas ref={ref} className="flow-background" data-flow-ready={ready||undefined} data-flow-fallback={fallback?'css':undefined} aria-hidden="true"/>}
